### ISSUE TITLE
Run time exceptions on 3.0.1 module

### ISSUE THREAD

**Issue by dariuszchlebek** [bluepayment-plugin/prestashop-plugin-1.7#14]
I started getting exceptions with new 3.0.1 version of module. Stack trace below:

[Mon Jan 29 20:32:00.206242 2024] [proxy_fcgi:error] [pid 487:tid 140256745531136] [client Y] AH01071: Got error 'PHP message: PHP Fatal error: Uncaught RuntimeException: Not supported serviceId "" - must be integer, string given in X/public_html/modules/bluepayment/src/OnlinePayments/Gateway.php:315\nStack trace:\n#0 X/public_html/modules/bluepayment/controllers/front/regulationsGet.php(60): BlueMedia\\OnlinePayments\\Gateway->__construct('', '', 'live')\n#1 X/public_html/modules/bluepayment/controllers/front/regulationsGet.php(34): BluePaymentRegulationsGetModuleFrontController->regulationsGet()\n#2 X/public_html/classes/controller/Controller.php(306): BluePaymentRegulationsGetModuleFrontController->initContent()\n#3 X/public_html/classes/Dispatcher.php(525): ControllerCore->run()\n#4 /X/public_html/index.php(28): DispatcherCore->dispatch()\n#5 {main}\n thrown in X/public_html/modules/bluepayment/src/On...', referer: X

**Comment by AutopayDevelopers** [comment]
Dzień dobry,

dziękujemy za zgłoszenie. Opisana sytuacja jest przez nas analizowana i jej rozwiązanie pojawi się w przyszłej wersji wtyczki 3.0.6. W przypadku dalszych pytań bardzo prosimy o kontakt bezpośrednio do działu supportu pod adresem https://developers.autopay.pl/kontakt

Pozdrawiamy
Zespół Autopay
